;食用方法:
;https://<转换api>?target=clash&append_sub_userinfo=true&config=<配置文件raw链>&emoji=true&fdn=true&include=&exclude=&udp=true&sort=true&new_name=true&url=<泡面订阅链>
;转换api建议使用sub官方&泡面家&自建

[custom]
clash_rule_base=https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/all-base.tpl
surfboard_rule_base=https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/all-base.tpl
surge_rule_base=https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/all-base.tpl
mellow_rule_base=https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/all-base.tpl
quan_rule_base=https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/all-base.tpl
quanx_rule_base=https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/all-base.tpl
loon_rule_base=https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/all-base.tpl
sssub_rule_base=https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/all-base.tpl
singbox_rule_base=https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/all-base.tpl

exclude_remarks=((到期)|(剩余流量)|(时间)|(官网)|(产品)|(先购买套餐)|(流量消耗)|(更新订阅)|(套餐到期)|(.*流量.*剩.*天)|(■等级警报■)|(\(限速\))|(\[限速\])|(\[游戏\])|(\[游戏专用\])|(\[将下线\])|(.*耗尽.*)|(近期下线)|(游戏专线)|(维护)|(测试节点)|(防失联地址)|(官方地址)|(官方网站)|(群组))

udp_flag=true

rename=!!import:https://raw.githubusercontent.com/xiwuaya/ccdrules/refs/heads/dev/ini/ReN-ver2.list

add_emoji=true
remove_old_emoji=true
emoji=!!import:https://raw.githubusercontent.com/xiwuaya/ccdrules/refs/heads/dev/ini/Emoji-ver2.list

custom_proxy_group=🔰 星辰大海`select`[]🎯 直连服务`[]🍱 自选A`[]🍱 自选B`[]🍱 自选C`[]🍱 自选D`[]🌮 手动选择`[]🍱 专线`[]🐞`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=🍱 自选A`select`[]REJECT`[]DIRECT`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others`🇭🇰`🇯🇵`🇹🇼`🇺🇸`🇷🇺`🇰🇷`🇸🇬`🇬🇧`🇩🇪`🇲🇾`^(?!🌸|🇨🇳).*`🇨🇳
custom_proxy_group=🍱 自选B`select`[]REJECT`[]DIRECT`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others`🇭🇰`🇯🇵`🇹🇼`🇺🇸`🇷🇺`🇰🇷`🇸🇬`🇬🇧`🇩🇪`🇲🇾`^(?!🌸|🇨🇳).*`🇨🇳
custom_proxy_group=🍱 自选C`select`[]REJECT`[]DIRECT`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others`🇭🇰`🇯🇵`🇹🇼`🇺🇸`🇷🇺`🇰🇷`🇸🇬`🇬🇧`🇩🇪`🇲🇾`^(?!🌸|🇨🇳).*`🇨🇳
custom_proxy_group=🍱 自选D`select`[]REJECT`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=🌮 手动选择`select`.*
custom_proxy_group=🍱 专线`select`[]🍱 专线Auto`广港`深港`[]REJECT
custom_proxy_group=🌍 国外媒体`select`[]🔰 星辰大海`[]🍱 专线`[]🍱 自选A`[]🍱 自选B`[]🍱 自选C`[]🎯 直连服务`[]🐞`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=📲 电报消息`select`[]🔰 星辰大海`[]🍱 专线`[]🍱 自选A`[]🍱 自选B`[]🍱 自选C`[]🎯 直连服务`[]🐞`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=🎮 游戏服务`select`[]🔰 星辰大海`[]🍱 专线`[]🍱 自选A`[]🍱 自选B`[]🍱 自选C`[]🎯 直连服务`[]🐞`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=🐼 微软服务`select`[]🎯 直连服务`[]🔰 星辰大海`[]🍱 专线`[]🍱 自选A`[]🍱 自选B`[]🍱 自选C`[]🐞`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=🌈 OpenAI`select`[]🔰 星辰大海`[]🎯 直连服务`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=🌈 CiciAI`select`[]🔰 星辰大海`[]🎯 直连服务`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=🍎 苹果服务`select`[]🎯 直连服务`[]🔰 星辰大海
custom_proxy_group=🌏 大陆服务`select`[]🎯 直连服务`(🇨🇳)`[]🔰 星辰大海
custom_proxy_group=📺 哔哩哔哩`select`[]🎯 直连服务`[]🔰 星辰大海`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=🥝 爱奇艺`select`[]🎯 直连服务`[]🔰 星辰大海`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=🐷 网易音乐`select`[]🎯 直连服务`(网易云)`(UnblockNetEaseMusic)`(🇨🇳)
custom_proxy_group=🚧 终末策略`select`[]🎯 直连服务`[]🔰 星辰大海
custom_proxy_group=📡 视频解析`select`[]🎯 直连服务`[]🔰 星辰大海
custom_proxy_group=🎥 奈飞影视`select`[]🔰 星辰大海`[]🍱 专线`[]🍱 自选A`[]🍱 自选B`[]🍱 自选C`[]🎯 直连服务`[]🐞`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=🙈 谷歌服务`select`[]🔰 星辰大海`[]🍱 专线`[]🍱 自选A`[]🍱 自选B`[]🍱 自选C`[]🎯 直连服务`[]🐞`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=🐻 LineTV`select`[]🎯 直连服务`[]🔰 星辰大海`[]🍱 专线`[]🍱 自选A`[]🍱 自选B`[]🍱 自选C`[]🎯 直连服务`[]🐞`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=🎬 推趣影音`select`[]🎯 直连服务`[]🔰 星辰大海`[]🍱 专线`[]🍱 自选A`[]🍱 自选B`[]🍱 自选C`[]🐞`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=💊 小米服务`select`[]🎯 直连服务`[]🔰 星辰大海`[]🐞`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others
custom_proxy_group=🐱 阿里巴巴`select`[]🎯 直连服务`(🇨🇳)
;custom_proxy_group=🍜 故障转移`fallback`[]🍱 自选D`[]🍱 专线`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇺🇸 美国`[]🇷🇺 俄罗斯`[]🗺 Others`http://connectivitycheck.gstatic.com/generate_204`300,5,180
custom_proxy_group=🚦 DMCA Sensitive`select`[]🎯 直连服务`[]🔰 星辰大海
custom_proxy_group=🥥 DNS Improvement`select`[]🎯 直连服务`(🇨🇳)`[]🔰 星辰大海
custom_proxy_group=🕸️ 局域网服务`select`[]🎯 直连服务`[]🔰 星辰大海
custom_proxy_group=🚀 SpeedTest`select`[]🎯 直连服务`[]🌮 手动选择

;mode c
;(-------------------[mode:C]-------------------)
custom_proxy_group=!!import:https://raw.githubusercontent.com/xiwuaya/ccdrules/refs/heads/dev/ini/Mode.C.conf
custom_proxy_group=🍱 专线Auto`url-test`广港`深港`[]REJECT`http://connectivitycheck.gstatic.com/generate_204`300,5,180
custom_proxy_group=🐞`url-test`[]🍱 自选A`[]🍱 自选B`[]🍱 自选C`http://connectivitycheck.gstatic.com/generate_204`90,5,180

;;

custom_proxy_group=🎯 直连服务`select`[]DIRECT
custom_proxy_group=🍥 政府网站`select`[]🎯 直连服务`[]🌏 大陆服务
custom_proxy_group=☠️ 软件验证`select`[]REJECT`[]🎯 直连服务`[]🔰 星辰大海
custom_proxy_group=⛔️ 广告服务`select`[]REJECT`[]🎯 直连服务
custom_proxy_group=⏰ 时间校准`select`[]🎯 直连服务

node_pref=(.*广港.*|.*深港.*)@skip_cert_verify_flag=true

enable_rule_generator=true
overwrite_original_rules=true
ruleset=🥥 DNS Improvement,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/DNS.list,10800
ruleset=☠️ 软件验证,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/App-Activation.list,10800
ruleset=⛔️ 广告服务,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Adblock/Adblock.list,10800
ruleset=⏰ 时间校准,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/NTP-Service.list,10800
ruleset=🍎 苹果服务,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Apple.list,10800
ruleset=📺 哔哩哔哩,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/BiliBiliHMT.list,10800
ruleset=📺 哔哩哔哩,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/BiliBili.list,10800
ruleset=🌈 OpenAI,surge:https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/AiDomain.list
ruleset=🌈 CiciAI,surge:https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/CiciAi.list
ruleset=🙈 谷歌服务,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Google.list,10800
ruleset=🍥 政府网站,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/Government-CN.list,10800
ruleset=🥝 爱奇艺,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/iQIYI-Intl.list,10800
ruleset=🥝 爱奇艺,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/iQIYI.list,10800
ruleset=🐻 LineTV,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/LineTV.list,10800
ruleset=🐼 微软服务,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Microsoft.list,10800
ruleset=🐷 网易音乐,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/NeteaseMusic.list,10800
ruleset=🎥 奈飞影视,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Netflix.list,10800
ruleset=📲 电报消息,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Telegram.list,10800
ruleset=🎬 推趣影音,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Twitch.list,10800
ruleset=📡 视频解析,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/Video-Crack.list,10800
ruleset=💊 小米服务,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Xiaomi.list,10800
ruleset=🚦 DMCA Sensitive,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/DMCA-Sensitive.list,10800
ruleset=🎯 直连服务,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/TeamViewer-CIDR.list,10800
ruleset=🕸️ 局域网服务,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/LAN-Special-Apps.list,10800
ruleset=🎮 游戏服务,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Game.list,10800
ruleset=🌍 国外媒体,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/GlobalMedia.list,10800
ruleset=🔰 星辰大海,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY.list,10800
ruleset=🐱 阿里巴巴,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Alibaba.list,10800
ruleset=🌏 大陆服务,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic.list,10800
ruleset=🌏 大陆服务,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/CCC-CN.list,10800
ruleset=🔰 星辰大海,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/CCC-Global.list,10800
ruleset=🚀 SpeedTest,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/SpeedTest.list,10800
ruleset=🎯 直连服务,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/Local-LAN.list,10800
ruleset=🌏 大陆服务,surge:https://raw.githubusercontent.com/LM-Firefly/Rules/master/CN-IP.list,10800
ruleset=🌏 大陆服务,[]GEOIP,CN
ruleset=🚧 终末策略,[]MATCH

;Rule base 偷懒不写，更新不及时，请查阅如下LM-Firefly配置文件的 '[template]' 部分:
;https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/CordCloud.ini
;update:23.06.18

[template]
clash.mixed_port=18888
;clash.redir_port=18890
clash.allow_lan=true
clash.log_level=info
clash.api_port=0.0.0.0:19090
clash.routing_mark=16666
singbox.ipv6=true
singbox.allow_lan=true
singbox.mixed_port=2080


;|------------Based on Firefly&EKyero&lhie1&tindy2013's&ACL4SSR profiles,Thanks lot------------|
;LM-Firefly: https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/CordCloud.ini
;connershua: https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/connershua_pro.ini
;lhie1:      https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/lhie1_clash.ini